name: Deploy documentation website

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

permissions:
  contents: write  # Needed for GitHub Pages deployment

jobs:
  deploy:
    runs-on: [base-dind-2204-amd64]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          echo "PATH=$PATH:$HOME/.local/bin" >> "$GITHUB_ENV"

      - name: Build and deploy MkDocs site
        run: |
          mkdocs gh-deploy --force

